import type { LexiconEntry } from "@/lib/types";

export type LexiconEnrichment = Partial<
  Pick<
    LexiconEntry,
    "ipa" | "phonics" | "fieldContext" | "meaning" | "association" | "example" | "exampleTranslation" | "related"
  >
> & {
  preferProfessional?: boolean;
};

const localLexiconEnrichments: Record<string, LexiconEnrichment> = {
  algebra: {
    preferProfessional: true,
    ipa: "/ˈældʒəbrə/",
    phonics: "AL-ge-bra; stress on al",
    fieldContext: "math foundation for ML",
    meaning: "代数；研究符号、方程和抽象运算规则。",
    association: "unknown x -> algebra",
    example: "Algebra gives the symbolic language behind linear models.",
    exampleTranslation: "Algebra 提供了线性模型背后的符号语言。",
    related: ["linear algebra", "equation", "matrix"],
  },
  analytical: {
    preferProfessional: true,
    ipa: "/ˌænəˈlɪtɪkəl/",
    phonics: "a-na-LY-ti-cal; stress on ly",
    fieldContext: "CIS 5800 course framing",
    meaning: "分析性的；强调用数学、推导和结构化方法理解问题。",
    association: "analysis -> analytical",
    example: "The course framing is geometrical, analytical, and computational.",
    exampleTranslation: "这门课的定位是几何的、分析的和计算的。",
    related: ["analysis", "geometrical", "computational"],
  },
  calculus: {
    preferProfessional: true,
    ipa: "/ˈkælkjələs/",
    phonics: "CAL-cu-lus; stress on cal",
    fieldContext: "math foundation for vision and ML",
    meaning: "微积分；研究变化率、导数、积分和连续变化。",
    association: "calculate change -> calculus",
    example: "Calculus helps describe how a loss changes with model parameters.",
    exampleTranslation: "Calculus 帮助描述 loss 如何随模型参数变化。",
    related: ["derivative", "gradient", "vector calculus"],
  },
  computational: {
    preferProfessional: true,
    ipa: "/ˌkɑːmpjuˈteɪʃənəl/",
    phonics: "com-pu-TA-tion-al; stress on ta",
    fieldContext: "CIS 5800 course framing",
    meaning: "计算性的；强调算法、程序和数值方法。",
    association: "compute -> computation -> computational",
    example: "Computational machine perception uses algorithms to interpret images.",
    exampleTranslation: "Computational machine perception 用算法来解释图像。",
    related: ["algorithm", "machine perception", "analytical"],
  },
  confirms: {
    preferProfessional: true,
    ipa: "/kənˈfɜːrmz/",
    phonics: "con-FIRMS; stress on firms",
    fieldContext: "academic notes",
    meaning: "确认；说明某个来源支持这个判断。",
    association: "confirm = make sure something is true",
    example: "Canvas course home page confirms the course framing.",
    exampleTranslation: "Canvas 课程主页确认了这门课的定位。",
    related: ["support", "verify", "evidence"],
  },
  electromagnetic: {
    preferProfessional: true,
    ipa: "/ɪˌlɛktroʊmæɡˈnɛtɪk/",
    phonics: "e-lec-tro-mag-NET-ic; stress on net",
    fieldContext: "CIS 5800 light and radiometry",
    meaning: "电磁的；和电场、磁场以及光波传播有关。",
    association: "electric + magnetic -> electromagnetic wave",
    example: "Visible light is part of the electromagnetic spectrum.",
    exampleTranslation: "可见光是 electromagnetic spectrum 的一部分。",
    related: ["electromagnetic radiation", "visible spectrum", "photon energy"],
  },
  "electromagnetic radiation": {
    preferProfessional: true,
    ipa: "/ɪˌlɛktroʊmæɡˈnɛtɪk ˌreɪdiˈeɪʃən/",
    phonics: "e-lec-tro-mag-NET-ic ray-di-A-tion",
    fieldContext: "CIS 5800 light and radiometry",
    meaning: "电磁辐射；以电磁波形式传播的能量，光就是其中一种。",
    association: "light as wave energy",
    example: "Cameras measure electromagnetic radiation in the visible spectrum.",
    exampleTranslation: "相机会测量 visible spectrum 中的 electromagnetic radiation。",
    related: ["visible spectrum", "photon energy", "radiometry"],
  },
  framing: {
    preferProfessional: true,
    ipa: "/ˈfreɪmɪŋ/",
    phonics: "frame /freɪm/ + -ing; stress on frame",
    fieldContext: "CIS 5800 course framing",
    meaning: "定位和理解框架；这里指这门课被如何定义和组织。",
    association: "frame = put boundaries around an idea; framing = how an idea is positioned",
    example: "Canvas course home page confirms the course framing as geometrical, analytical, and computational machine perception.",
    exampleTranslation: "Canvas 课程主页确认了这门课的定位：它从几何、分析和计算三个角度来理解 machine perception。",
    related: ["perspective", "positioning", "course framing"],
  },
  flux: {
    preferProfessional: true,
    ipa: "/flʌks/",
    phonics: "flux; short u like duck",
    fieldContext: "CIS 5800 radiometry",
    meaning: "通量；单位时间穿过某个表面或区域的总量，在光学里常指光能流量。",
    association: "flow through an area",
    example: "Radiant flux measures total light energy transferred per second.",
    exampleTranslation: "Radiant flux 衡量每秒传递的总光能。",
    related: ["radiometry", "watts", "irradiance", "solid angle"],
  },
  geometrical: {
    preferProfessional: true,
    ipa: "/ˌdʒiːəˈmɛtrɪkəl/",
    phonics: "ge-o-MET-ri-cal; stress on met",
    fieldContext: "CIS 5800 course framing",
    meaning: "几何的；强调空间、形状、坐标和投影关系。",
    association: "geometry -> geometrical",
    example: "A geometrical view of vision focuses on shape, camera, and projection.",
    exampleTranslation: "视觉中的 geometrical 视角关注形状、相机和投影关系。",
    related: ["geometry", "projection", "homography"],
  },
  intensity: {
    preferProfessional: true,
    ipa: "/ɪnˈtɛnsəti/",
    phonics: "in-TEN-si-ty; stress on ten",
    fieldContext: "CIS 5800 image formation",
    meaning: "强度；在图像里常指像素亮度或光的强弱。",
    association: "intense = strong; intensity = strength of light or signal",
    example: "Image intensity mixes illumination, material, and shape.",
    exampleTranslation: "图像强度混合了光照、材质和形状信息。",
    related: ["brightness", "illumination", "radiance", "pixel"],
  },
  intuition: {
    preferProfessional: true,
    ipa: "/ˌɪntuˈɪʃən/",
    phonics: "in-tu-I-tion; stress on i",
    fieldContext: "lecture explanation",
    meaning: "直觉理解；先抓住概念背后的感觉和物理意义，不只是公式。",
    association: "intuition = what the idea feels like before proof",
    example: "The intuition is that irradiance asks how much light a surface receives.",
    exampleTranslation: "这里的 intuition 是：irradiance 问的是一个表面接收到多少光。",
    related: ["concept", "physical meaning", "radiometry"],
  },
  isotropic: {
    preferProfessional: true,
    ipa: "/ˌaɪsəˈtrɑːpɪk/",
    phonics: "i-so-TROP-ic; stress on trop",
    fieldContext: "CIS 5800 reflectance and light models",
    meaning: "各向同性的；性质在所有方向上都一样，不依赖观察或入射方向。",
    association: "iso = same; tropic = direction",
    example: "An isotropic material reflects light the same way after rotating around the normal.",
    exampleTranslation: "Isotropic 材质绕法线旋转后，反射光的方式仍然一样。",
    related: ["anisotropic", "BRDF", "Lambertian"],
  },
  pixel: {
    preferProfessional: true,
    ipa: "/ˈpɪksəl/",
    phonics: "pix + el; stress on pix",
    fieldContext: "computer vision",
    meaning: "像素；图像中最小的采样单位。",
    association: "picture element -> pixel",
    example: "A pixel records image intensity at one image location.",
    exampleTranslation: "一个 pixel 记录图像中某个位置的强度。",
    related: ["image", "intensity", "sensor"],
  },
  linear: {
    preferProfessional: true,
    ipa: "/ˈlɪniər/",
    phonics: "LIN-ear; stress on lin",
    fieldContext: "math foundation for ML",
    meaning: "线性的；满足加法和数乘规则，常用于描述矩阵、向量和模型关系。",
    association: "line -> linear",
    example: "A linear model combines features with weights.",
    exampleTranslation: "Linear model 会用权重把特征线性组合起来。",
    related: ["linear algebra", "matrix", "vector"],
  },
  "linear algebra": {
    preferProfessional: true,
    ipa: "/ˈlɪniər ˈældʒəbrə/",
    phonics: "LIN-ear AL-ge-bra; stress on lin and al",
    fieldContext: "math foundation for ML, vision, graphics",
    meaning: "线性代数；研究向量、矩阵、线性变换和方程组，是机器学习和计算机视觉的基础。",
    association: "vectors + matrices + transformations",
    example: "Linear algebra represents images, projections, and neural network layers with vectors and matrices.",
    exampleTranslation: "Linear algebra 用向量和矩阵表示图像、投影和神经网络层。",
    related: ["vector", "matrix", "projection", "eigenvector"],
  },
  "photon energy": {
    preferProfessional: true,
    ipa: "/ˈfoʊtɑːn ˈɛnərdʒi/",
    phonics: "PHO-ton EN-er-gy; stress on pho and en",
    fieldContext: "CIS 5800 light and radiometry",
    meaning: "光子能量；单个 photon 携带的能量，和光的频率有关。",
    association: "one packet of light -> energy",
    example: "Photon energy increases as light frequency increases.",
    exampleTranslation: "光的频率越高，photon energy 越大。",
    related: ["photon", "electromagnetic radiation", "visible spectrum"],
  },
  radiometry: {
    preferProfessional: true,
    ipa: "/ˌreɪdiˈɑːmətri/",
    phonics: "ray-di-OM-e-try; stress on om",
    fieldContext: "CIS 5800 image formation",
    meaning: "辐射度量学；用物理量描述光能如何发出、传播和被表面接收。",
    association: "measure light energy",
    example: "Radiometry connects light energy to image intensity.",
    exampleTranslation: "Radiometry 把光能和图像强度联系起来。",
    related: ["radiance", "irradiance", "flux", "solid angle"],
  },
  "scalar-valued function": {
    preferProfessional: true,
    ipa: "/ˈskeɪlər ˈvæljuːd ˈfʌŋkʃən/",
    phonics: "SCA-lar VAL-ued FUNC-tion",
    fieldContext: "vector calculus and optimization",
    meaning: "标量值函数；输入可以是向量，但输出是一个数，比如 loss function。",
    association: "many inputs -> one number",
    example: "A loss function is often a scalar-valued function of model parameters.",
    exampleTranslation: "Loss function 通常是关于模型参数的 scalar-valued function。",
    related: ["gradient", "vector calculus", "optimization"],
  },
  sensor: {
    preferProfessional: true,
    ipa: "/ˈsɛnsər/",
    phonics: "sense + -or; stress on sense",
    fieldContext: "camera model",
    meaning: "传感器；相机中接收光并形成图像信号的部件。",
    association: "sense light -> sensor",
    example: "The sensor response turns incoming light into image measurements.",
    exampleTranslation: "sensor response 会把进入相机的光转成图像测量值。",
    related: ["camera", "pixel", "image formation"],
  },
  "solid angle": {
    preferProfessional: true,
    ipa: "/ˈsɑːlɪd ˈæŋɡəl/",
    phonics: "SOL-id ANG-le; stress on sol and ang",
    fieldContext: "CIS 5800 radiometry",
    meaning: "立体角；二维角度在三维空间里的对应概念，用来描述方向范围。",
    association: "angle in 3D",
    example: "Radiance is measured per unit solid angle.",
    exampleTranslation: "Radiance 会按单位 solid angle 来度量。",
    related: ["radiance", "steradian", "direction"],
  },
  "visible spectrum": {
    preferProfessional: true,
    ipa: "/ˈvɪzəbəl ˈspɛktrəm/",
    phonics: "VIS-i-ble SPEC-trum; stress on vis and spec",
    fieldContext: "CIS 5800 light and cameras",
    meaning: "可见光谱；人眼和普通相机能感知的一段电磁波范围。",
    association: "visible colors from violet to red",
    example: "RGB cameras capture part of the visible spectrum.",
    exampleTranslation: "RGB 相机捕捉 visible spectrum 的一部分。",
    related: ["electromagnetic radiation", "wavelength", "color"],
  },
  "image formation": {
    preferProfessional: true,
    ipa: "/ˈɪmɪdʒ fɔːrˈmeɪʃən/",
    phonics: "image + formation; main stress on formation",
    fieldContext: "CIS 5800",
    meaning: "图像形成；从场景、光照、材质、相机到图像的过程。",
    association: "world + light + camera -> image",
    example: "Image formation explains why vision is an inverse problem.",
    exampleTranslation: "Image formation 解释了为什么视觉是一个反问题。",
    related: ["radiance", "reflectance", "projection"],
  },
  "inverse problem": {
    preferProfessional: true,
    ipa: "/ˌɪnˈvɜːrs ˈprɑːbləm/",
    phonics: "in-VERSE PROB-lem; stress on verse and prob",
    fieldContext: "computer vision",
    meaning: "反问题；从结果反推原因，比如从图像反推形状、材质和光照。",
    association: "output -> hidden causes",
    example: "Computer vision is hard because image understanding is an inverse problem.",
    exampleTranslation: "Computer vision 很难，因为图像理解本质上是从结果反推原因。",
    related: ["image formation", "shape", "illumination"],
  },
  gradient: {
    preferProfessional: true,
    ipa: "/ˈɡreɪdiənt/",
    phonics: "GRA-di-ent; stress on gra",
    fieldContext: "vector calculus and optimization",
    meaning: "梯度；标量函数对输入变量变化最快方向的向量。",
    association: "which direction makes the value rise fastest",
    example: "Gradient descent follows the negative gradient to reduce loss.",
    exampleTranslation: "Gradient descent 沿负梯度方向移动来降低 loss。",
    related: ["derivative", "vector calculus", "optimization"],
  },
  "vector calculus": {
    preferProfessional: true,
    ipa: "/ˈvɛktər ˈkælkjələs/",
    phonics: "VEC-tor CAL-cu-lus; stress on vec and cal",
    fieldContext: "math foundation for vision, optimization, and physics-driven ML",
    meaning: "向量微积分；把微积分扩展到向量场和多变量函数，常用于梯度、散度、旋度和优化。",
    association: "vector + change -> gradient field",
    example: "Vector calculus explains gradients used in optimization and physical models.",
    exampleTranslation: "Vector calculus 解释了优化和物理模型中使用的梯度。",
    related: ["gradient", "calculus", "optimization", "physics-driven ML"],
  },
};

export function getLocalLexiconEnrichment(text: string): LexiconEnrichment | undefined {
  const direct = localLexiconEnrichments[lexiconLookupKey(text)];
  if (direct) return direct;
  return undefined;
}

export function lexiconLookupKey(text: string) {
  return text.trim().toLowerCase().replace(/\s+/g, " ");
}
